import Link from "next/link";
import { Footer, Header, PageHero } from "../site-components";

export default function About() {
  return <><Header /><main>
    <PageHero eyebrow="About KAMP" title="Manufacturing knowledge built over generations." intro="KAMP Stamping has manufactured electrical stampings and motor components since 1984, combining long-standing industry knowledge with a modern production base in Rajasthan." />
    <section className="section"><div className="container image-story"><div className="image-story__image image-story__image--tall"><img src="/images/factory.jpg" alt="KAMP Stamping manufacturing facility in Bhiwadi" /></div><div><p className="eyebrow">Our story</p><h2>From Noida to Bhiwadi.</h2><p className="prose-large">Founded by Kewal Aggarwal, the business grew from a small electrical-stamping operation in Noida into an established manufacturing company serving customers across India. Today, KAMP brings that experience to a two-acre facility in Bhiwadi.</p><p>Our focus remains straightforward: understand the requirement, control the process, deliver consistent quality and honour the production schedule.</p></div></div></section>
    <section className="section section--soft"><div className="container"><div className="section-heading"><div><p className="eyebrow">Leadership</p><h2>Experience on the floor and in the business.</h2></div></div><div className="leader-grid"><article><span>Founder & Director</span><h3>Kewal Aggarwal</h3><p>A manufacturing entrepreneur with four decades of experience building electrical-stamping businesses and customer relationships across India.</p></article><article><span>Managing Director</span><h3>Amit Aggarwal</h3><p>A software engineer by education who brings technical thinking and operational focus to the next phase of KAMP’s manufacturing growth.</p></article></div></div></section>
    <section className="section section--ink"><div className="container facts-grid"><div><span>Legal status</span><strong>Private Limited Company</strong></div><div><span>Incorporated</span><strong>26 August 2011</strong></div><div><span>Facility</span><strong>2 acres</strong></div><div><span>Team</span><strong>50–100 people</strong></div><div><span>GST</span><strong>08AAECK4546N1Z2</strong></div><div><span>Annual turnover</span><strong>₹40–60 crore</strong></div></div></section>
    <section className="cta-band"><div className="container cta-band__inner"><div><p className="eyebrow eyebrow--light">Work with KAMP</p><h2>Bring us your next requirement.</h2></div><Link className="button button--light" href="/contact/">Contact the team</Link></div></section>
  </main><Footer /></>;
}
